apply from: "$rootDir/buildSrc/androidLib.gradle"

android {
    namespace 'net.maxsmr.android.recyclerview'
}

dependencies {

    api "com.google.android.material:material:$materialVersion"
    api "androidx.recyclerview:recyclerview:$androidxRecyclerViewVersion"

    api "com.hannesdorfmann:adapterdelegates4-kotlin-dsl:$adapterdelegates4KotlinVersion"

//    api project(":easyadapter")
//    api (name: 'easyadapter', ext:'aar')
}